const fields = {
  required_information: [
    { name: 'Full Name', type: 'text', editable: false, placeholder: 'John Doe', id: 'fullName' },
    { name: 'Client Type', type: 'dropdown', placeholder: 'Select client type', id: 'clientType' },
    { name: 'Partner', type: 'dropdown', placeholder: 'Select partner', id: 'partner' },
    { name: 'Manager', type: 'dropdown', placeholder: 'Select manager', id: 'manager' },
  ],
  company_details: [
    { name: 'Company Number', type: 'text', placeholder: 'Enter company number', id: 'company_number' },
    { name: 'Incorporation Date', type: 'date', placeholder: 'Select a date', id: 'incorporation_date' },
    { name: 'Registered Address', type: 'text', multiline: true, placeholder: 'Enter company address', id: 'registered_address' },
    { name: 'Company Postal Address', type: 'text', multiline: true, placeholder: 'Enter company postal address', id: 'company_postal_address' }, // Assuming this is the intended field
    { name: 'Invoice Address', type: 'dropdown', placeholder: 'Enter invoice address', id: 'invoice_address' },
    { name: 'Company Email', type: 'text', placeholder: 'company@example.com', id: 'company_email' },
    { name: 'Company Telephone', type: 'phone', placeholder: '(555) 000-0000', id: 'company_phone_number' },
    { name: 'Turnover', type: 'text', placeholder: 'Enter amount', id: 'turnover' },
    { name: 'Date of Trading', type: 'date', placeholder: 'Select date', id: 'date_of_trading' },
    { name: 'SIC Code', type: 'text', placeholder: 'e.g., 62020', id: 'sic_code' },
    { name: 'Nature of Business', type: 'text', placeholder: 'Brief description', id: 'nature_of_business' },
    { name: 'Corporation Tax Office', type: 'text', placeholder: 'Enter office name', id: 'corporation_tax_office' },
    { name: 'Company UTR', type: 'text', placeholder: '10-digit number', id: 'company_utr' },
    { name: 'Companies House Authentication Code', type: 'text', placeholder: 'Enter code', id: 'companies_house_authentication_code' },
  ],
  main_contact: [
    { name: 'Full Name', type: 'text', editable: false, placeholder: 'John Doe' },
    { name: 'Incorporation Date', type: 'date', placeholder: 'Select date' },
    { name: 'Date of Birth', type: 'date', placeholder: 'Select date' },
    { name: 'Deceased', type: 'date', placeholder: 'Select option' },
    { name: 'Postal Address', type: 'text', multiline: true, placeholder: 'Enter company postal address' },
    { name: 'Previous Address', type: 'text',multiline: true, placeholder: 'Enter previous address' },
    { name: 'Telephone number', type: 'phone', placeholder: '(555) 000-0000' },
    { name: 'Mobile Number', type: 'phone', placeholder: '(555) 000-0000' },
    { name: 'NI Number', type: 'text', placeholder: 'AB123456C' },
    { name: 'Personal UTR Number', type: 'text', placeholder: '10-digit number' },
    { name: 'Terms Signed', type: 'date', placeholder: 'Select date' },
    { name: 'Marital Status', type: 'dropdown', placeholder: 'Select status' },
    { name: 'Nationality', type: 'dropdown', placeholder: 'Select nationality' },
    { name: 'Preferred Language', type: 'dropdown', placeholder: 'Select language' },
  ],
  secondary_contact: [
    { name: 'Full Name', type: 'text', editable: false, placeholder: 'John Doe' },
    { name: 'Incorporation Date', type: 'date', placeholder: 'Select date' },
    { name: 'Date of Birth', type: 'date', placeholder: 'Select date' },
    { name: 'Deceased', type: 'date', placeholder: 'Select option' },
    { name: 'Postal Address', type: 'text', multiline: true, placeholder: 'Enter company postal address' },
    { name: 'Previous Address', type: 'text',multiline: true, placeholder: 'Enter previous address' },
    { name: 'Telephone number', type: 'phone', placeholder: '(555) 000-0000' },
    { name: 'Mobile Number', type: 'phone', placeholder: '(555) 000-0000' },
    { name: 'NI Number', type: 'text', placeholder: 'AB123456C' },
    { name: 'Personal UTR Number', type: 'text', placeholder: '10-digit number' },
    { name: 'Terms Signed', type: 'date', placeholder: 'Select date' },
    { name: 'Marital Status', type: 'dropdown', placeholder: 'Select status' },
    { name: 'Nationality', type: 'dropdown', placeholder: 'Select nationality' },
    { name: 'Preferred Language', type: 'dropdown', placeholder: 'Select language' },
  ],
  income_details: [
    { name: 'Previous Income', type: 'text', placeholder: 'Enter your previous income', id: 'previous_income' },
    { name: 'Current Income', type: 'text', placeholder: 'Enter your current income', id: 'current_income' },
    { name: 'IR35 Notes', type: 'text', multiline: true, placeholder: 'Enter IR 35 Notes', id: 'ir_35_notes' },
  ],
  previous_accountant: [
    { name: 'Accountant Email Address', type: 'text', placeholder: 'Enter email address', id: 'email_address' },
    { name: 'Accountant Details', type: 'text', multiline: true, placeholder: 'Enter your accountant details', id: 'accountant_details' },
    { name: 'Send First Clearance Email', type: 'date', placeholder: 'Select date', id: 'date_first_clearance_email_was_sent' },
    { name: 'Automatically Request Every', type: 'dropdown', placeholder: 'Select', id: 'automatically_request_every' },
    { name: 'Last Requested', type: 'date', placeholder: 'Select a date', id: 'last_requested' },
  ],
  other_details: [
    { name: 'Referred By', type: 'text', placeholder: 'Say who referred you', id: 'referred_by' },
    { name: 'Initial Contact', type: 'date', placeholder: 'DD/MM/YYYY', id: 'initial_contact' },
    { name: 'Profession', type: 'text', placeholder: 'What do you do?', id: 'profession' },
    { name: 'Website', type: 'text', placeholder: 'Enter URL', id: 'website' },
    { name: 'Twitter Handle', type: 'text', placeholder: 'Enter your handle', id: 'twitter' },
    { name: 'Facebook URL', type: 'text', placeholder: 'Enter Facebook URL', id: 'facebook' },
    { name: 'LinkedIn URL', type: 'text', placeholder: 'Enter LinkedIn URL', id: 'linkedin' },
    { name: 'Instagram Handle', type: 'text', placeholder: 'Enter your IG handle', id: 'instagram' },
  ],
  services_required: [
    { name: 'Accounts', type: 'checkbox' },
    { name: 'Bookkeeping', type: 'checkbox' },
    { name: 'VAT returns', type: 'checkbox' },
    { name: 'P11D', type: 'checkbox' },
    { name: 'CT600 Return', type: 'checkbox' },
    { name: 'Payroll', type: 'checkbox' },
    { name: 'Auto-enrolment', type: 'checkbox' },
    { name: 'Confirmation statement', type: 'checkbox' },
    { name: 'Management accounts', type: 'checkbox' },
    { name: 'CIS', type: 'checkbox' },
    { name: 'Fee protection service', type: 'checkbox' },
    { name: 'Registered address', type: 'checkbox' },
    { name: 'Bill payment', type: 'checkbox' },
    { name: 'Consultation/Advice', type: 'checkbox' },
    { name: 'Software', type: 'checkbox' },
  ],
  accounts_and_returns_details: [
    { name: 'Accounts Period End', type: 'date', placeholder: 'Select a date', id: 'account_period_end' },
    { name: 'CH Year End (Companies House)', type: 'date', placeholder: 'Select a date', id: 'ch_year_end' },
    { name: 'HMRC Year End', type: 'date', placeholder: 'Select a date', id: 'hmrc_year_end' },
    { name: 'CH Accounts Next Due', type: 'date', placeholder: '24/09/2024', id: 'ch_accounts_next_due' },
    { name: 'Corporation Tax Amount Due', type: 'number', placeholder: 'Enter amount', prefix: '€', id: 'corporation_tax_amount_due' },
    { name: 'CT Payment Reference', type: 'text', placeholder: 'Enter amount', id: 'ct_payment_reference' },
    { name: 'Tax Office', type: 'text', placeholder: 'Enter TaxOffice', id: 'tax_office' },
    { name: 'Accounts Latest Action', type: 'dropdown', placeholder: 'Select an option', id: 'accounts_latest_action' },
    { name: 'Accounts Latest Action Date', type: 'date', placeholder: 'Select a Date', id: 'accounts_latest_action_date' },
    { name: 'Accounts Records Received', type: 'date', placeholder: 'Select a Date', id: 'accounts_records_received' },
    { name: 'Accounts Progress Note', type: 'text', multiline: true, placeholder: 'Enter progress note', id: 'accounts_progress_note' },
    { name: 'CT600 Latest Action', type: 'dropdown', placeholder: 'Select an option', id: 'ct600_latest_action' },
    { name: 'CT600 Latest Action Date', type: 'date', placeholder: 'Select a date', id: 'ct600_latest_action_date' },
    { name: 'CT600 Progress Note', type: 'text', multiline: true, placeholder: 'Enter your progress note', id: 'ct600_progress_note' }
  ],
  confirmation_statement: [
    { name: 'Confirmation Statement Date', type: 'date', placeholder: 'Select a date', id: 'confirmation_statement_date' },
    { name: 'Confirmation Statement Due', type: 'date', placeholder: 'Select a date', id: 'confirmation_statement_due' },
    { name: 'Latest Action', type: 'dropdown', placeholder: 'Records Requested', id: 'latest_action' },
    { name: 'Latest Action Date', type: 'date', placeholder: 'Select a Date', id: 'latest_action_date' },
    { name: 'Records Received', type: 'date', placeholder: 'Select a date', id: 'records_received' },
    { name: 'Progress Note', type: 'text', placeholder: 'Enter your current income', multiline: true, id: 'progress_note' },
    { name: 'Officers', type: 'text', placeholder: 'Enter officers', multiline: true, id: 'officers' },
    { name: 'Share Capital', type: 'text', placeholder: 'Enter your capital', multiline: true, id: 'share_capital' },
    { name: 'Shareholders', type: 'text', placeholder: 'Enter your shareholders', multiline: true, id: 'shareholders' },
    { name: 'People with significant control', type: 'text', placeholder: 'Enter information', multiline: true, id: 'people_with_significant_control' }
  ],
  vat_details: [
    { name: 'VAT Frequency', type: 'dropdown', placeholder: 'Quarterly', id: 'vat_frequency' },
    { name: 'VAT Period End', type: 'date', placeholder: 'Select a date', id: 'vat_period_end' },
    { name: 'Next Return Due', type: 'date', placeholder: 'Select a date', id: 'next_return_due' },
    { name: 'VAT Bill Amount', type: 'number', placeholder: 'Enter amount', prefix: '€', id: 'vat_bill_amount' },
    { name: 'VAT Bill Date', type: 'date', placeholder: 'Select a Date', id: 'vat_bill_date' },
    { name: 'Latest Action', type: 'dropdown', placeholder: 'Select', id: 'latest_action' },
    { name: 'Latest Action Date', type: 'date', placeholder: 'Select a Date', id: 'latest_action_date' },
    { name: 'Records Received', type: 'date', placeholder: 'Select a Date', id: 'records_received' },
    { name: 'Progress Note', type: 'text', placeholder: 'Enter progress notes', id: 'progress_note' },
    { name: 'VAT Member State', type: 'dropdown', placeholder: 'Select', id: 'vat_member_state' },
    { name: 'VAT Number', type: 'text', placeholder: 'Enter', id: 'vat_number' },
    { name: 'VAT Address', type: 'text', placeholder: 'Enter address', id: 'vat_address' },
    { name: 'Date of Registration', type: 'date', placeholder: 'Select a Date', id: 'date_of_registration' },
    { name: 'Effective Date', type: 'date', placeholder: 'Select date', id: 'effective_date' },
    { name: 'Estimated Turnover', type: 'text', placeholder: 'Enter amount', prefix: '€', id: 'estimated_turnover' },
    { name: 'Applied for MTD', type: 'date', placeholder: 'Select date', id: 'date_applied_for_mtd' },
    { name: 'Transfer of Going Concern', type: 'checkbox', id: 'transfer_of_going_concern' },
    { name: 'Involved in any Other Business', type: 'checkbox', id: 'involved_in_any_other_business' },
    { name: 'MTD Ready', type: 'checkbox', id: 'mtd_ready' },
    { name: 'Direct Debit', type: 'checkbox', id: 'direct_debit' },
    { name: 'Standard Scheme', type: 'checkbox', id: 'standard_scheme' },
    { name: 'Call Accounting Scheme', type: 'checkbox', id: 'call_accounting_scheme' },
    { name: 'Retail Scheme', type: 'checkbox', id: 'retail_scheme' },
    { name: 'Margin Scheme', type: 'checkbox', id: 'margin_scheme' },
    { name: 'Flat Rate', type: 'checkbox', id: 'flat_scheme' },
    { name: 'Flat Rate Category', type: 'dropdown', placeholder: 'Select category', id: 'flat_rate_category' },
    { name: 'Month of Last Quarter Submitted', type: 'dropdown', placeholder: 'Select month', id: 'month_of_last_quarter_submitted' },
    { name: 'Box 5 of Last Quarter Submitted', type: 'dropdown', placeholder: 'Enter comments', id: 'box5_of_last_quarter_submitted' },
    { name: 'General Notes', type: 'text', multiline: true, placeholder: 'Enter notes', id: 'general_notes' },
  ],
  paye_details: [
    { name: 'Employer Reference', type: 'text', placeholder: 'Enter reference', id: 'employers_reference' }, 
    { name: 'Accounts Office Reference', type: 'text', placeholder: 'Enter reference', id: 'account_office_reference' },
    { name: 'Years Required', type: 'dropdown', placeholder: 'Enter years', id: 'years_required' },
    { name: 'PAYE Frequency', type: 'dropdown', id: 'paye_frequency' }, // Assuming this maps to a boolean
    { name: 'Number of Employees', type: 'text', placeholder: 'Enter number', id: 'number_of_employees' },
    { name: 'Salary Details', type: 'text', multiline: true, placeholder: 'Enter salary details', id: 'salary_details' },
    { name: 'First Pay Date', type: 'date', id: 'first_pay_date' }, // Assuming maps to boolean
    { name: 'RTI Deadline', type: 'date', placeholder: 'Select date', id: 'rti_deadline' },
    { name: 'PAYE Scheme Ceased', type: 'date', placeholder: 'Select date', id: 'paye_scheme_ceased' },
    { name: 'PAYE Latest Action', type: 'dropdown', placeholder: 'Select date', id: 'paye_latest_action' },
    { name: 'PAYE Latest Action Date', type: 'date', placeholder: 'Enter payment details', id: 'paye_latest_action_date' },
    { name: 'PAYE Records Received', type: 'date', placeholder: 'Select frequency', id: 'paye_records_received' }, // Assuming this is what was meant
    { name: 'PAYE Progress Note', type: 'text', multiline: true, placeholder: 'Enter notices', id: 'paye_progress_note' },
    { name: 'General Notes', type: 'text', multiline: true, placeholder: 'Write extra notes', id: 'general_notes' }, // Assuming maps to boolean
    { name: 'Applied for MTD', type: 'date', placeholder: 'Select quarter', id: 'date_applied_for_mtd' }, // New ID added
    { name: 'Box 5 of Last Quarter Submitted', type: 'dropdown', placeholder: 'Enter notice details', id: 'box5_of_last_quarter_submitted' }, // New ID added
  ],
  auto_enrolment: [
    { name: 'Auto Enrolment Latest Action', type: 'dropdown', placeholder: 'Select date', id: 'auto_enrolment_latest_action' }, // Corrected typo
    { name: 'Auto Enrolment Latest Action Date', type: 'date', id: 'auto_enrolment_latest_action_date' },
    { name: 'Auto Enrolment Records Received', type: 'date', id: 'auto_enrolment_records_received' },
    { name: 'Auto Enrolment Progress Note', type: 'text', multiline: true, placeholder: 'Enter progress notes', id: 'auto_enrolment_progress_note' },
    { name: 'Auto Enrolment Staging', type: 'dropdown', placeholder: 'Select staging status', id: 'auto_enrolment_staging' },
    { name: 'Postponement Date', type: 'date', placeholder: 'Select date', id: 'postponement_date' },
    { name: 'The Pensions Regulator Opt-out Date', type: 'date', placeholder: 'Enter ID/TLN number', id: 'the_pensions_regulator_opt_out_date' },
    { name: 'Re-Enrollment Date', type: 'date', placeholder: 'Select date', id: 're_enrollment_date' },
    { name: 'Pension Provider', type: 'text', placeholder: 'Enter pension ID', id: 'pension_provider' },
    { name: 'Pension ID', type: 'text', placeholder: 'Enter pension ID', id: 'pension_id' },
    { name: 'Declaration of Compliance Date', type: 'date', placeholder: 'Select date', id: 'declaration_of_compliance_date' },
    { name: 'Declaration of Compliance Submission', type: 'date', id: 'declaration_of_compliance_submission' },
  ],
  p11d: [
    { name: 'Next P11D Return Date', type: 'date', placeholder: 'Select date', id: 'next_p11d_return_date' }, // Assuming this is part of p11d
    { name: 'Latest P11D Submitted', type: 'date', placeholder: 'Select date', id: 'lastest_p11d_submitted' }, 
    { name: 'P11D Latest Action', type: 'dropdown', placeholder: 'Select date', id: 'p11d_latest_action' }, 
    { name: 'P11D Latest Action Date', type: 'date', multiline: true, placeholder: 'Enter note', id: 'p11d_latest_action_date' },
    { name: 'P11D Records Received', type: 'date', placeholder: 'Enter action', id: 'p11d_records_received' },
    { name: 'P11D Progress Notes', type: 'text', multiline: true, placeholder: 'Enter notes', id: 'p11d_progress_note' }, 
  ],
  registration: [
    { name: 'Letter of Engagement', type: 'file', placeholder: 'Upload file', id: 'signed_letter_of_engagement' },
    { name: 'Write Comments', type: 'text', multiline: true, placeholder: 'Tell us if you have anything to say...', id: 'comments' },
  ],
  identityVerification: [
    { name: 'Verification', options: true },
  ]
};

export default fields;