const fields = {
  required: [
    { name: 'Full Name', type: 'text', editable: false, placeholder: 'John Doe' },
    { name: 'Client Type', type: 'dropdown', placeholder: 'Select client type' },
    { name: 'Partner', type: 'dropdown', placeholder: 'Select partner' },
    { name: 'Manager', type: 'dropdown', placeholder: 'Select manager' },
  ],
  company: [
    { name: 'Company Number', type: 'text', placeholder: 'Enter company number' },
    { name: 'Incorporation Date', type: 'date', placeholder: 'Select a date' },
    { name: 'Registered Address', type: 'text', multiline: true, placeholder: 'Enter company address' },
    { name: 'Company Postal Address', type: 'text', multiline: true, placeholder: 'Enter company postal address' },
    { name: 'Invoice Address', type: 'dropdown', placeholder: 'Enter invoice address' },
    { name: 'Company Email', type: 'text', placeholder: 'company@example.com' },
    { name: 'Company Telephone', type: 'phone', placeholder: '(555) 000-0000' },
    { name: 'Turnover', type: 'text', placeholder: 'Enter amount' },
    { name: 'Turnover Detail', type: 'dropdown', placeholder: 'Enter amount' },
    { name: 'Date of Trading', type: 'date', placeholder: 'Select date' },
    { name: 'SIC Code', type: 'text', placeholder: 'e.g., 62020' },
    { name: 'Nature of Business', type: 'text', placeholder: 'Brief description' },
    { name: 'Corporation Tax Office', type: 'text', placeholder: 'Enter office name' },
    { name: 'Company UTR', type: 'text', placeholder: '10-digit number' },
    { name: 'Companies House Authentication Code', type: 'text', placeholder: 'Enter code' },
  ],
  mainContact: [
    { name: 'Full Name', type: 'text', editable: false, placeholder: 'John Doe' },
    { name: 'Incorporation Date', type: 'date', placeholder: 'Select date' },
    { name: 'Date of Birth', type: 'date', placeholder: 'Select date' },
    { name: 'Deceased', type: 'date', placeholder: 'Select option' },
    { name: 'Postal Address', type: 'text', multiline: true, placeholder: 'Enter company postal address' },
    { name: 'Previous Address', type: 'text',multiline: true, placeholder: 'Enter previous address' },
    { name: 'Telephone number', type: 'phone', placeholder: '(555) 000-0000' },
    { name: 'Mobile Number', type: 'phone', placeholder: '(555) 000-0000' },
    { name: 'NI Number', type: 'text', placeholder: 'AB123456C' },
    { name: 'Personal UTR Number', type: 'text', placeholder: '10-digit number' },
    { name: 'Terms Signed', type: 'date', placeholder: 'Select date' },
    { name: 'Marital Status', type: 'dropdown', placeholder: 'Select status' },
    { name: 'Nationality', type: 'dropdown', placeholder: 'Select nationality' },
    { name: 'Preferred Language', type: 'dropdown', placeholder: 'Select language' },
  ],
  secondaryContact: [
    { name: 'Full Name', type: 'text', editable: false, placeholder: 'John Doe' },
    { name: 'Incorporation Date', type: 'date', placeholder: 'Select date' },
    { name: 'Date of Birth', type: 'date', placeholder: 'Select date' },
    { name: 'Deceased', type: 'date', placeholder: 'Select option' },
    { name: 'Postal Address', type: 'text', multiline: true, placeholder: 'Enter company postal address' },
    { name: 'Previous Address', type: 'text',multiline: true, placeholder: 'Enter previous address' },
    { name: 'Telephone number', type: 'phone', placeholder: '(555) 000-0000' },
    { name: 'Mobile Number', type: 'phone', placeholder: '(555) 000-0000' },
    { name: 'NI Number', type: 'text', placeholder: 'AB123456C' },
    { name: 'Personal UTR Number', type: 'text', placeholder: '10-digit number' },
    { name: 'Terms Signed', type: 'date', placeholder: 'Select date' },
    { name: 'Marital Status', type: 'dropdown', placeholder: 'Select status' },
    { name: 'Nationality', type: 'dropdown', placeholder: 'Select nationality' },
    { name: 'Preferred Language', type: 'dropdown', placeholder: 'Select language' },
  ],
  incomeDetails: [
    { name: 'Previous Income', type: 'text', placeholder: 'Enter your previous income' },
    { name: 'Current Income', type: 'text', placeholder: 'Enter your current income' },
    { name: 'IR35 Notes', type: 'text', multiline: true, placeholder: 'Enter IR 35 Notes' },
  ],

  previousAccountant: [
    { name: 'Accountant Email Address', type: 'text', placeholder: 'Enter email address' },
    { name: 'Accountant Details', type: 'text', multiline: true, placeholder: 'Enter your accountant details' },
    { name: 'Send First Clearance Email', type: 'date', placeholder: 'Select date' },
    { name: 'Automatically Request Every', type: 'dropdown', placeholder: 'Select' },
    { name: 'Last Requested', type: 'date', placeholder: 'Select a date' },
  ],

  otherDetails: [
    { name: 'Referred By', type: 'text', placeholder: 'Say who referred you' },
    { name: 'Initial Contact', type: 'date', placeholder: 'DD/MM/YYYY' },
    { name: 'Profession', type: 'text', placeholder: 'What do you do?' },
    { name: 'Website', type: 'text', placeholder: 'Enter URL' },
    { name: 'Twitter Handle', type: 'text', placeholder: 'Enter your handle' },
    { name: 'Facebook URL', type: 'text', placeholder: 'Enter Facebook URL' },
    { name: 'LinkedIn URL', type: 'text', placeholder: 'Enter LinkedIn URL' },
    { name: 'Instagram Handle', type: 'text', placeholder: 'Enter your IG handle' },
  ],

  serviceRequired: [
    { name: 'Accounts', type: 'checkbox' },
    { name: 'Bookkeeping', type: 'checkbox' },
    { name: 'VAT returns', type: 'checkbox' },
    { name: 'P60', type: 'checkbox' },
    { name: 'CT600 Return', type: 'checkbox' },
    { name: 'Payroll', type: 'checkbox' },
    { name: 'Auto-enrolment', type: 'checkbox' },
    { name: 'Confirmation statement', type: 'checkbox' },
    { name: 'Management accounts', type: 'checkbox' },
    { name: 'CIS', type: 'checkbox' },
    { name: 'Fee protection service', type: 'checkbox' },
    { name: 'Registered address', type: 'checkbox' },
    { name: 'Bill payment', type: 'checkbox' },
    { name: 'Consultation/Advice', type: 'checkbox' },
    { name: 'Software', type: 'checkbox' },
  ],
  accountReturnDetails: [
    { name: 'Accounts Period End', type: 'date', placeholder: 'Select a date' },
    { name: 'CH Year End (Companies House)', type: 'date', placeholder: 'Select a date' },
    { name: 'HMRC Year End', type: 'date', placeholder: 'Select a date' },
    { name: 'CH Accounts Next Due', type: 'date', placeholder: '24/09/2024' },
    { name: 'Corporation Tax Amount Due', type: 'number', placeholder: 'Enter amount', prefix: '€' },
    { name: 'Tax Due HMRC Year End', type: 'date', placeholder: 'Select a date' },
    { name: 'CT Payment Reference', type: 'text', placeholder: 'Enter amount' },
    { name: 'TaxOffice', type: 'text', placeholder: 'Enter TaxOffice' },
    { name: 'Accounts Latest Action', type: 'dropdown', placeholder: 'Select an option' },
    { name: 'Accounts Latest Action Date', type: 'date', placeholder: 'Select a Date' },
    { name: 'Accounts Records Received', type: 'date', placeholder: 'Select a Date' },
    { name: 'Accounts Progress Note', type: 'text', multiline: true, placeholder: 'Enter progress note' },
    { name: 'CT600 Latest Action', type: 'dropdown', placeholder: 'Select an option' },
    { name: 'CT600 Latest Action Date', type: 'date', placeholder: 'Select a date' },
    { name: 'CT600 Progress Note', type: 'text', multiline: true, placeholder: 'Enter your progress note' }
  ],
  confirmationStatement: [
    { name: 'Confirmation Statement Date', type: 'date', placeholder: 'Select a date' },
    { name: 'Confirmation Statement Due', type: 'date', placeholder: 'Select a date' },
    { name: 'Latest Action', type: 'dropdown', placeholder: 'Records Requested' },
    { name: 'Latest Action Date', type: 'date', placeholder: 'Select a Date' },
    { name: 'Records Received', type: 'date', placeholder: 'Select a date' },
    { name: 'Progress Note', type: 'text', placeholder: 'Enter your current income', multiline: true },
    { name: 'Officers', type: 'text', placeholder: 'Enter officers', multiline: true },
    { name: 'Share Capital', type: 'text', placeholder: 'Enter your capital', multiline: true },
    { name: 'Shareholders', type: 'text', placeholder: 'Enter your shareholders', multiline: true },
    { name: 'People with significant control', type: 'text', placeholder: 'Enter information', multiline: true }
  ],
  vatDetails: [
    { name: 'VAT Frequency', type: 'dropdown', placeholder: 'Quarterly' },
    { name: 'VAT Period End', type: 'date', placeholder: 'Select a date' },
    { name: 'Next Return Due', type: 'date', placeholder: 'Select a date' },
    { name: 'VAT Bill Amount', type: 'number', placeholder: 'Enter amount', prefix: '€' },
    { name: 'VAT Bill Date', type: 'date', placeholder: 'Select a Date' },
    { name: 'Latest Action', type: 'dropdown', placeholder: 'Select' },
    { name: 'Latest Action Date', type: 'date', placeholder: 'Select a Date' },
    { name: 'Records Received', type: 'date', placeholder: 'Select a Date' },
    { name: 'Progress Note', type: 'text', placeholder: 'Enter progress notes' },
    { name: 'VAT Member State', type: 'dropdown', placeholder: 'Select' },
    { name: 'VAT Number', type: 'text', placeholder: 'Enter' },
    { name: 'VAT Address', type: 'text', placeholder: 'Enter address' },
    { name: 'Date of Registration', type: 'date', placeholder: 'Select a Date' },
    { name: 'Effective Date', type: 'date', placeholder: 'Select date' },
    { name: 'Estimated Turnover', type: 'text', placeholder: 'Enter amount', prefix: '€' },
    { name: 'Applied for MTD', type: 'date', placeholder: 'Enter EORI number' },
    { name: 'Transfer of Going Concern', type: 'checkbox' },
    { name: 'Involved in any Other Business', type: 'checkbox' },
    { name: 'Direct Debit', type: 'checkbox' },
    { name: 'Standard Scheme', type: 'checkbox' },
    { name: 'Call Accounting Scheme', type: 'checkbox' },
    { name: 'Retail Scheme', type: 'checkbox' },
    { name: 'Margin Scheme', type: 'checkbox' },
    { name: 'Flat Rate', type: 'checkbox' },
    { name: 'Flat Rate Category', type: 'dropdown', placeholder: 'Select category' },
    { name: 'Month of Last Quarter Submitted', type: 'dropdown', placeholder: 'Select month' },
    { name: 'Box 5 of Last Quarter Submitted', type: 'dropdown', placeholder: 'Enter comments' },
    { name: 'General Notes', type: 'text', multiline: true, placeholder: 'Enter notes' },
  ],
  payeDetails: [
    { name: 'Employer Reference', type: 'text', placeholder: 'Enter reference' },
    { name: 'Payroll Office Number', type: 'text', placeholder: 'Enter number' },
    { name: 'Accounts Office Reference', type: 'text', placeholder: 'Enter reference' },
    { name: 'PAYE Registered', type: 'checkbox' },
    { name: 'PAYE Scheme', type: 'dropdown', placeholder: 'Select scheme' },
    { name: 'Date PAYE Started', type: 'date', placeholder: 'Select date' },
    { name: 'Annual Payroll Submission Made', type: 'checkbox' },
    { name: 'PAYE Latest Return Date', type: 'date', placeholder: 'Select date' },
    { name: 'PAYE Year End Submission', type: 'date', placeholder: 'Select date' },
    { name: 'PAYE Payment Due', type: 'date', placeholder: 'Select date' },
    { name: 'PAYE Payment Made', type: 'text', placeholder: 'Enter payment details' },
    { name: 'Payroll Frequency', type: 'dropdown', placeholder: 'Select frequency' },
    { name: 'Statutory Notices', type: 'text', multiline: true, placeholder: 'Enter notices' },
    { name: 'Applied for SPS', type: 'checkbox' },
    { name: 'PAYE and Last Quarter Submitted', type: 'dropdown', placeholder: 'Select quarter' },
    { name: 'Submitted Notice', type: 'text', placeholder: 'Enter notice details' },
  ],
  autoEnrollment: [
    { name: 'Auto Enrolment Staging Date', type: 'date', placeholder: 'Select date' },
    { name: 'Auto Enrolment Letter Received', type: 'checkbox' },
    { name: 'Auto Enrolment Review Required', type: 'checkbox' },
    { name: 'Auto Enrolment Progress Note', type: 'text', multiline: true, placeholder: 'Enter progress notes' },
    { name: 'Auto Enrolment Staging', type: 'dropdown', placeholder: 'Select staging status' },
    { name: 'Postponement Date', type: 'date', placeholder: 'Select date' },
    { name: 'The Pensions Regulator ID/TLN Number', type: 'text', placeholder: 'Enter ID/TLN number' },
    { name: 'AE Enrollment Date', type: 'date', placeholder: 'Select date' },
    { name: 'Pension ID', type: 'text', placeholder: 'Enter pension ID' },
    { name: 'Declaration of Compliance Date', type: 'date', placeholder: 'Select date' },
    { name: 'Declaration of Compliance Submitted', type: 'checkbox' },
  ],
  pid: [
    { name: 'PID Start Date', type: 'date', placeholder: 'Select date' },
    { name: 'PID Latest Review', type: 'date', placeholder: 'Select date' },
    { name: 'PID Latest Action Date', type: 'date', placeholder: 'Select date' },
    { name: 'PID Progress Note', type: 'text', multiline: true, placeholder: 'Enter note' },
    { name: 'PID Latest Action', type: 'text', placeholder: 'Enter action' },
    { name: 'PID Resource Notes', type: 'text', multiline: true, placeholder: 'Enter notes' },
    { name: 'PID Progress Now', type: 'text', placeholder: 'Enter progress' },
    { name: 'Status', type: 'dropdown', placeholder: 'Select status' },
  ],
  registration: [
    { name: 'Letter of Engagement', type: 'file', placeholder: 'Upload file' },
    { name: 'Write Comments', type: 'text', multiline: true, placeholder: 'Tell us if you have anything to say...' },
  ],
  identityVerification: [
    { name: 'Verification', options: true },
  ]
};

export default fields;